SexiVirt/sexivirt.Web/Models/ViewModels/PhotoView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sexivirt.Web.Models.ViewModels
{
    public class PhotoView
    {
        public int ID { get; set; }

        public string FilePath { get; set; }

        public bool IsCover { get; set; }

        public bool Checked { get; set; }
    }
}

SexiVirt/sexivirt.Web/Areas/Default/Controllers/AlbumController.cs
using sexivirt.Model;
using sexivirt.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sexivirt.Web.Areas.Default.Controllers
{
    public class AlbumController : DefaultController
    {
        public ActionResult Index(int id = 0)
        {
            if (id == 0)
            {
                if (CurrentUser != null)
                {
                    return View(CurrentUser);
                }
            }
            else
            {
                var user = Repository.Users.FirstOrDefault(p => p.ID == id);
                return View(user);
            }

            return RedirectToNotFoundPage;
        }

        public ActionResult All()
        {
            if (CurrentUser != null)
            {
                return View(CurrentUser);
            }
            return RedirectToNotFoundPage;
        }

        [Authorize]
        public ActionResult Create()
        {
            var albumView = new AlbumView();

            return View("Edit", albumView);
        }

        public ActionResult Delete(int id)
        {
            Repository.DeleteAlbum(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var album = Repository.Albums.FirstOrDefault(p => p.ID == id);

            if (album != null && CurrentUser.ID == album.UserID)
            {
                var albumView = (AlbumView)ModelMapper.Map(album, typeof(Album), typeof(AlbumView));
                return View(albumView);
            }
            return RedirectToNotFoundPage;
        }
        public ActionResult Edit(AlbumView albumView)
        {
            if (albumView.Photos == null || albumView.Photos.Count == 0)
            {
                ModelState.AddModelError("Photos", "Добавьте фото");
            }
            if (ModelState.IsValid)
            {
                var album = (Album)ModelMapper.Map(albumView, typeof(AlbumView), typeof(Album));
                album.UserID = CurrentUser.ID;

                var listPhotos = (List<Photo>)ModelMapper.Map(albumView.Photos, typeof(List<PhotoView>), typeof(List<Photo>));
                if (album.ID == 0)
                {
                    Repository.CreateAlbum(album);
                }
                else
                {
                    Repository.UpdateAlbum(album);
                }

                Repository.UpdateAlbumPhotos(listPhotos, album.ID);
                return RedirectToAction("Index");
            }
            return View(albumView);
        }


        public ActionResult PhotoItem(string filePath)
        {
            var photoView = new PhotoView()
            {
                FilePath = filePath
            };
            return PartialView(photoView);
        }


        public ActionResult Item(int id)
        {
            var album = Repository.Albums.FirstOrDefault(p => p.ID == id);
            if (album != null)
            {
                if (album.HasAccess(CurrentUser))
                {
                    return View(album);
                }
            }
            return RedirectToNotFoundPage;

        }

        [HttpGet]
        public ActionResult BuyAlbum(int id)
        {
            var album = Repository.Albums.FirstOrDefault(p => p.ID == id);
            if (album != null && album.Price > 0)
            {
                return PartialView(album);
            }
            return null;
        }

        public ActionResult Photo(int id)
        {
            var photo = Repository.Photos.FirstOrDefault(p => p.ID == id);
            if (photo != null) 
            {
                return PartialView(photo);
            }
            return null;
        }

        public ActionResult ChangePhoto(int id, bool next = true)
        {
            var photo = Repository.ChangePhoto(id, next);
            if (photo != null)
            {

                return PartialView("Photo", photo);
            }
            return RedirectToNotFoundPage;
        }

        public ActionResult AllPhoto(int id)
        {
            var photo = Repository.Photos.FirstOrDefault(p => p.ID == id);
            if (photo != null)
            {
                return PartialView(photo);
            }
            return null;
        }

        public ActionResult ChangeAllPhoto(int id, bool next = true)
        {
            var photo = Repository.ChangeAllPhoto(id, next);
            if (photo != null)
            {

                return PartialView("AllPhoto", photo);
            }
            return RedirectToNotFoundPage;
        }


        [HttpPost]
        public ActionResult BuyAlbum(int id, int userId)
        {
            var user = Repository.Users.FirstOrDefault(p => p.ID == userId);
            var album = Repository.Albums.FirstOrDefault(p => p.ID == id);

            if (album != null && user != null)
            {
                if (album.HasAccess(user))
                {
                    return Json(new { result = "ok", id = album.ID });
                }

                if (CurrentUser.Money > album.Price)
                {
                    var price = album.Price.Value;
                    var incomePrice = price * 0.8;
                    var feePrice = price * 0.2;

                    var moneyDetail = new MoneyDetail()
                    {
                        UserID = CurrentUser.ID,
                        Sum = -price,
                        Description = string.Format("Оплата за альбом {0} ({1})", album.Name, album.User.FirstName),
                        Type = (int)MoneyDetail.TypeEnum.PayForAlbum,
                    };

                    var incomeMoney = new MoneyDetail()
                    {
                        UserID = album.UserID,
                        Sum = incomePrice,
                        Description = string.Format("Открытие альбома {0} ({1})", album.Name, CurrentUser.FirstName),
                        Type = (int)MoneyDetail.TypeEnum.GetForAlbum,
                    };

                    var feeMoney = new MoneyDetail()
                    {
                        UserID = null,
                        Sum = feePrice,
                        Description = string.Format("Комиссия за открытие альбома {0} ({1}) {2}", album.Name, album.User.FirstName, CurrentUser.FirstName),
                        Type = (int)MoneyDetail.TypeEnum.Fee,
                        IsFee = true,
                    };

                    var guid = Repository.CreateTripleMoneyDetail(moneyDetail, incomeMoney, feeMoney);

                    var access = new AlbumAccess()
                    {
                        AlbumID = album.ID,
                        UserID = user.ID,
                    };
                    Repository.CreateAlbumAccess(access);
                    Repository.SubmitMoney(guid);

                    var feed = new Feed()
                    {
                        ActionType = (int)Feed.ActionTypeEnum.PayForAlbumAccess,
                        AlbumAccessID = access.ID,
                        UserID = album.UserID,
                        ActorID = CurrentUser.ID,
                        IsNew = true,
                        Text = string.Format("Ваш баланс пополнен на {0} р. Поздравляем!", incomeMoney.Sum.ToString("F0"))
                    };
                    Repository.CreateFeed(feed);

                    return Json(new { result = "ok", id = album.ID });
                }
                return Json(new { result = "need-money" });
            }
            return Json(new { result = "ok" });
        }
    }
}

SexiVirt/sexivirt.Web/Areas/Default/Views/Album/All.cshtml
@model sexivirt.Model.User

@{
    ViewBag.Title = "Все фото";
    Layout = "~/Areas/Default/Views/Shared/_Layout.cshtml";
    var currentUser = ((sexivirt.Web.Controllers.BaseController)ViewContext.Controller).CurrentUser;
}
@section header {
    @Scripts.Render("~/Scripts/default/photo.js")
}
<div class="middle">
    @Html.Action("MainMenu", "Home")
    <div class="content">
        <section class="change-albums">
            <h1>Все фото <a href="@Url.Action("Index", "Album", new { id = Model.ID })">К альбомам</a></h1>
            <div class="album-list">
                @foreach (var item in Model.SubPhotos)
                {
                    <div class="photo-item userPhotoItem" data-id="@item.ID">
                        <img src="@item.FilePath?w=155&h=155&mode=crop" alt="">
                    </div>
                }
            </div>
        </section>
    </div>
</div>

SexiVirt/sexivirt.Web/Areas/Default/Views/Album/AllPhoto.cshtml
@model Photo 
<div class="popupBg"></div>
<div class="popup picture">
    <div class="pp_close popup-close">×</div>
    <div class="pp_title">Фото @Model.NumberOfUser из @Model.UserCount</div>
    <div class="picturt-wrapper">
        <img src="@Model.FilePath?maxwidth=600&maxheight=600" alt="" />
        <div class="right-arrow changePictUser" data-id="@Model.ID" data-next="false"></div>
        <div class="left-arrow changePictUser" data-id="@Model.ID" data-next="true"></div>
    </div>
</div>

SexiVirt/sexivirt.Web/Areas/Default/Views/Album/BuyAlbum.cshtml
@model Album
@{
    var currentUser = ((sexivirt.Web.Controllers.BaseController)ViewContext.Controller).CurrentUser;
}

<div class="popupBg"></div>
<div class="popup open-album pp-type1">
    <div class="pp_close close-popup">×</div>
    <div class="pp_title">@Model.Name</div>
    <div class="pp_text">закрытый альбом</div>
    <div class="ca_album">
        <div class="albumImg first close"><img src="/Content/images/photo/albums/close_@(Model.User.GenderStr).png" alt=""></div>
        <div class="albumImg first"><img src="@Model.FirstPhoto?w=158&h=158&mode=crop" alt=""></div>
        <div class="albumImg second close"><img src="/Content/images/photo/albums/close_@(Model.User.GenderStr).png" alt=""></div>
        <div class="albumImg second"><img src="@Model.SecondPhoto?w=158&h=158&mode=crop" alt=""></div>
        <div class="ca_photoNumber">@Model.PhotosCount фото</div>
    </div>
    <div class="pp_desc">@Model.User.FirstName @(Model.User.Sex ? "закрыл" : "закрыла") свой альбом от посторонних. Но вы можете открыть этот альбом. После этого он будет доступен вам всегда. Стоимость этого альбома:</div>
    <div class="pp_albumPrice">@Model.Price @Model.Price.Value.CountWord("рубль", "рубля", "рублей")</div>
    <button class="ppa_but greenBut" id="OpenAlbumBtn" data-id="@Model.ID" data-userid="@currentUser.ID">Открыть альбом</button>
    <span class="pp_cancel close-popup">Нет, спасибо</span>
</div>

SexiVirt/sexivirt.Web/Areas/Default/Views/Album/Edit.cshtml
@model AlbumView
@{
    ViewBag.Title = Model.ID == 0 ? "Добавить альбом" : "Изменить альбом";
    Layout = "~/Areas/Default/Views/Shared/_Layout.cshtml";
}

@section header {
    @Scripts.Render("~/bundles/fineuploader")
    @Scripts.Render("~/Scripts/default/edit-album.js")
}

<div class="middle">
    @Html.Action("MainMenu", "Home")
    <div class="content">
        <section class="change-albums album-edit">
            <h1><a href="@Url.Action("Index", "Album")">Альбомы</a><a href="@Url.Action("All", "Album")">Все фото</a></h1>
            @using (Html.BeginForm("Edit", "Album", FormMethod.Post))
            {
                @Html.TextBox("Name", Model.Name, new { placeholder = "Введите название альбома" })
                <div class="wrapper">
                    <div class="paid">
                        @Html.CheckBox("IsPayed", Model.IsPayed, new { @class = "checkboxEmul" })
                        <span class="checkboxLabel">Платный альбом</span>
                    </div>
                    <div class="cost" id="CostWrapper">
                        <span>Стоимость</span>
                        @Html.TextBox("Price", Model.Price)
                        <span>р. — комиссия сервиса 20%. <span id="CostInfoWrapper">Вы получите <span id="PriceWrapper">0</span> р.</span></span>
                    </div>
                </div>
                <div id="AlbumWrapper">
                    @if (Model.Photos != null)
                    {
                        foreach (var photo in Model.Photos)
                        {
                            @Html.Partial("PhotoItem", photo)
                        }
                    }
                </div>
                @Html.ValidationMessage("Photos")
                <div class="photo-item add">
                    <div class="add-wrapper" id="UploadPhoto">
                        Добавить<br>фото
                    </div>
                </div>
                <div class="footer">
                    <div class="delete" id="DeletePhoto">
                        Удалить выделенные фото
                    </div>
                    <div class="cover" id="MakeCover">
                        Сделать обложкой альбома
                    </div>
                    <button class="greenBut">Сохранить изменения</button>
                </div>
            }
        </section>
    </div>
</div>
@Html.Partial("UploadTemplatePhoto")

SexiVirt/sexivirt.Web/Areas/Default/Views/Album/Index.cshtml
@model User
@{
    var currentUser = ((sexivirt.Web.Controllers.BaseController)ViewContext.Controller).CurrentUser;
    if (currentUser != null && currentUser.ID == Model.ID)
    {
        ViewBag.Title = "Мои альбомы";
    }
    else
    {
        ViewBag.Title = "Альбомы";
    }
    Layout = "~/Areas/Default/Views/Shared/_Layout.cshtml";
}

@section header {
    @Scripts.Render("~/Scripts/default/money.js")
    @Scripts.Render("~/Scripts/default/album-access.js")
}

<div class="middle">
    @Html.Action("MainMenu", "Home")
    <div class="content">
        <section class="c_albums clear">
            <h1>
                Альбомы
                @if (currentUser != null && Model.ID == currentUser.ID)
                {
                    <a href="@Url.Action("All", "Album")">Все фото</a>
                }
            </h1>
            <div class="c_userName @Model.GenderStr">
                <a href="@Url.Action("Index", "User", new {id = Model.ID })">@Model.FirstName</a>
                <div class="c_userPhoto  @Model.GenderStr">
                    <img src="@Model.FullAvatarPath?w=52&h=52&mode=crop" alt="">
                </div>
            </div>
            @foreach (var album in Model.SubAlbums)
            {
                @Html.Partial("AlbumPartial", album)
            }
            @if (currentUser != null && currentUser.ID == Model.ID)
            {
                <div class="new-album">
                    <a href="@Url.Action("Create", "Album")">
                        <div class="add-album">
                            <div class="plus"></div>
                            Новый<br>альбом
                        </div>
                    </a>
                </div>
            }
        </section>
    </div>
</div>

SexiVirt/sexivirt.Web/Areas/Default/Views/Album/Item.cshtml
@model sexivirt.Model.Album

@{
    ViewBag.Title = Model.Name;
    Layout = "~/Areas/Default/Views/Shared/_Layout.cshtml";
    var currentUser = ((sexivirt.Web.Controllers.BaseController)ViewContext.Controller).CurrentUser;
}
@section header {
    @Scripts.Render("~/Scripts/default/photo.js")
}
<div class="middle">
    @Html.Action("MainMenu", "Home")
    <div class="content">
        <section class="change-albums">
            <h1>@Model.Name <a href="@Url.Action("Index", "Album", new { id = Model.UserID })">К альбомам</a></h1>
            <div class="album-list">
                @foreach (var item in Model.SubPhotos)
                {
                    <div class="photo-item albumPhotoItem" data-id="@item.ID">
                        <img src="@item.FilePath?w=155&h=155&mode=crop" alt="">
                    </div>
                }
            </div>
            @if (currentUser != null && currentUser.ID == Model.UserID)
            {
                <div class="footer">
                    <div class="edit">
                        <a href="@Url.Action("Edit", "Album", new {id = Model.ID })">Редактировать альбом</a>
                    </div>
                    <div class="delete">
                        <a href="@Url.Action("Delete", "Album", new { id = Model.ID })" class="delete-action">Удалить альбом</a>
                    </div>
                </div>
            }
        </section>
    </div>
</div>

SexiVirt/sexivirt.Web/Areas/Default/Views/Album/Photo.cshtml
@model Photo 
<div class="popupBg"></div>
<div class="popup picture">
    <div class="pp_close popup-close">×</div>
    <div class="pp_title">Фото @Model.NumberOfAlbum из @Model.AlbumCount</div>
    <div class="picturt-wrapper">
        <img src="@Model.FilePath?maxwidth=600&maxheight=600" alt="" />
        <div class="right-arrow changePict" data-id="@Model.ID" data-next="false"></div>
        <div class="left-arrow changePict" data-id="@Model.ID" data-next="true"></div>
    </div>
</div>

SexiVirt/sexivirt.Web/Areas/Default/Views/Album/PhotoItem.cshtml
@model PhotoView
<div class="photo-item @(Model.Checked ? "selected" : "") @(Model.IsCover ? "active" : "")">
    @{
        var guid = Guid.NewGuid().ToString("N");
    }
    @Html.Hidden("Photos.index", guid)
    @Html.Hidden("Photos[" + guid + "].ID", Model.ID)
    @Html.Hidden("Photos[" + guid + "].FilePath", Model.FilePath)
    @Html.Hidden("Photos[" + guid + "].IsCover", Model.IsCover, new { @class = "CoverInput" })
    <img src="@Model.FilePath?w=155&h=155&mode=crop" alt="">
    @Html.CheckBox("Photos["+guid +"].Checked", Model.Checked, new { @class = "checkboxEmul" })
</div>

SexiVirt/sexivirt.Web/Areas/Default/Views/Album/UploadTemplatePhoto.cshtml
<script type="text/template" id="qq-template-bootstrap">
    <div class="qq-uploader-selector qq-uploader col-md-12">
        <div class="qq-upload-drop-area-selector qq-upload-drop-area col-md-12 hidden" qq-hide-dropzone>
            <span>Переместите файлы сюда</span>
        </div>
        <div class="qq-upload-button-selector qq-upload-button" style="width: auto;">
            <div>Добавить<br>фото</div>
        </div>
        <span class="qq-drop-processing-selector qq-drop-processing hidden">
            <span>Обработка...</span>
            <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
        </span>
        <ul class="qq-upload-list-selector qq-upload-list hidden" style="margin-top: 10px; text-align: center;">
            <li>
                <div class="qq-progress-bar-container-selector">
                    <div class="qq-progress-bar-selector qq-progress-bar"></div>
                </div>
                <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                <span class="qq-upload-file-selector qq-upload-file"></span>
                <span class="qq-upload-size-selector qq-upload-size"></span>
                <a class="qq-upload-cancel-selector qq-upload-cancel" href="#">Cancel</a>
                <span class="qq-upload-status-text-selector qq-upload-status-text"></span>
            </li>
        </ul>
    </div>
</script>